### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxr-api#10]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by jim-krueger** [comment]
GlassFish 5.1 Release Tracker updated
