### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxr-api#24]
- [ ] Integrate to Eclipse GlassFish
- [ ] Pass all CTS/TCK tests

#10 must be finished before starting working on this task.

**Comment by jim-krueger** [comment]
@m0mus Who is going to do this task?  Is there a deadline and instructions?  Thanks

**Comment by lukasj** [comment]
see https://github.com/eclipse-ee4j/glassfish/pull/22654
