### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxr-api#3]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by kwsutter** [comment]
Will be working with Jim Krueger to get these pipelines done for the Stable API project.  Starting with this jaxr-api pipeline first.

**Comment by m0mus** [comment]
@kwsutter Can you please assign yourself or Jim to all tests you are planning to take. It's needed to reserve it, so others don't take it, and for tracking purposed. Thanks!

**Comment by jckofbyron** [comment]
@m0mus I am now a committer on ee4j.jakartaee-stable, however I still am unable to assign any of these issues to myself.  Is there an additional step I must take to get authority?   Thanks

**Comment by m0mus** [comment]
@jckofbyron Congratulations! Please check that you have your GitHub ID linked to your Eclipse account in your Eclipse profile. Add it there if you don't. If you have it there, please contact @eclipsewebmaster using BugZilla, they will help you.

**Comment by jim-krueger** [comment]
Jenkins Build CI/CD pipeline  (first pass) is created (awaiting GPG and OSSRH Setup).  I also may need to adjust the maven commands:
https://jenkins.eclipse.org/jakartaee-stable/job/JAXR-API%20master%20build/    (master build)
https://jenkins.eclipse.org/jakartaee-stable/job/JAXR-api_EE4J_8%20build/          (ee4j_8 build)

**Comment by jim-krueger** [comment]
Jenkin CI/CD build pipelines are green. Closing issue:

https://jenkins.eclipse.org/jakartaee-stable/job/JAXR-API%20master%20build/
https://jenkins.eclipse.org/jakartaee-stable/job/JAXR-api_EE4J_8%20build/
