### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxr-api#4]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by kwsutter** [comment]
Will be working with Jim Krueger to get these pipelines done for the Stable API project.   Still waiting for Jim's committership to come through...

**Comment by m0mus** [comment]
@kwsutter I've seen an email that it's done. Possibly will need to wait until changes are synchronised.

**Comment by jim-krueger** [comment]
The release job is correct, but hitting some issues in execution.  I will leave this issue open:
https://jenkins.eclipse.org/jakartaee-stable/job/JAXR-API-Release/
