### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish 5.1 for XML Registries

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jaxr-api#42]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Eclipse Glassfish 5.1](https://eclipse-ee4j.github.io/glassfish/download)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta XML Registries 1.0](https://jakarta.ee/specifications/xml-registries/1.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta XML Registries TCK](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-xml-registries-tck-1.0.0.zip), SHA-256:
  `fbe1ac6f6fc66e36ce7d0d9778e4ca28976d0db98887b7d944322d864e8996f5`
- [x] Public URL of TCK Results Summary:<br/>
  [TCK Results Summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-xml-registries/1.0/TCK-Results) 
- [x] Any Additional Specification Certification Requirements:<br/>
  None
- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Centos 7, Apache Derby, UDDI Registry (JWSDP)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
The TCK download link ought to be updated to: 
https://download.eclipse.org/jakartaee/xml-registries/1.0/eclipse-xml-registries-tck-1.0.0.zip or
https://download.eclipse.org/jakartaee/xml-registries/1.0/?d
